# Generated by Django 2.0.7 on 2018-08-10 06:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bkName', models.CharField(max_length=128, unique=True)),
                ('authorName', models.CharField(max_length=128)),
                ('publisher', models.CharField(max_length=128)),
                ('pubversion', models.IntegerField()),
                ('price', models.IntegerField()),
                ('pubDateTime', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.IntegerField()),
                ('sold', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pubDateTime'],
            },
        ),
    ]
